version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn server:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend
    restart: unless-stopped
    hostname: "frontend"
    ports:
      - "443:443"
    depends_on:
      - backend