CREATE TABLE courses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  code TEXT,
  ects INTEGER,
  semester INTEGER,
  status TEXT,
  type TEXT
);

INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Γραμμική Άλγεβρα', 'K03', 6, 1, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Διακριτά Μαθηματικά', 'K09', 7, 1, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Εισαγωγή στην Πληροφορική και στις Τηλεπικοινωνίες', 'ΓΠ07', 2, 1, 'NotTaken', 'GeneralEd');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Εισαγωγή στον Προγραμματισμό', 'K04', 7, 1, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Εργαστήριο Λογικής Σχεδίασης', 'K02ε', 2, 1, 'NotTaken', 'OptionalLab');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Λογική Σχεδίαση', 'K02', 6, 1, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ανάλυση Ι', 'K01', 8, 2, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Αρχιτεκτονική Υπολογιστών Ι', 'K14', 7, 2, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Δομές Δεδομένων και Τεχνικές Προγραμματισμού', 'K08', 7, 2, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Εφαρμοσμένα Μαθηματικά', 'K20β', 6, 2, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ηλεκτρομαγνητισμός – Οπτική και Σύγχρονη Φυσική', 'K12', 8, 2, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ανάλυση ΙΙ', 'K06', 8, 3, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Αντικειμενοστραφής Προγραμματισμός', 'K10', 8, 3, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Εργαστήριο Κυκλωμάτων και Συστημάτων', 'K11ε', 2, 3, 'NotTaken', 'OptionalLab');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Πιθανότητες και Στατιστική', 'K13', 6, 3, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Σήματα και Συστήματα', 'K11', 6, 3, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Αλγόριθμοι και Πολυπλοκότητα', 'K17', 8, 4, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Δίκτυα Επικοινωνιών I', 'K16', 6, 4, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Εργαστήριο Δικτύων Επικοινωνιών Ι', 'K16ε', 2, 4, 'NotTaken', 'OptionalLab');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Συστήματα Επικοινωνιών', 'K21', 7, 4, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Σχεδίαση και Χρήση Βάσεων Δεδομένων', 'K29', 7, 4, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Αριθμητική Ανάλυση', 'K15', 6, 5, 'NotTaken', 'TrackCompulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Αρχές Γλωσσών Προγραμματισμού', 'ΘΠ01', 6, 5, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Αρχιτεκτονική Υπολογιστών ΙΙ', 'K30', 6, 5, 'NotTaken', 'TrackCompulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Γραφικά Ι', 'ΘΠ02', 6, 5, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Δίκτυα Επικοινωνιών II', 'K33', 6, 5, 'NotTaken', 'TrackCompulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Εργαστήριο Δικτύων Επικοινωνιών Ι', 'K16ε', 2, 5, 'NotTaken', 'OptionalLab');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Κύματα, Κυματοδηγοί, Κεραίες', 'ΕΠ05', 6, 5, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Λειτουργικά Συστήματα', 'K22', 8, 5, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Παράλληλα Συστήματα', 'ΘΠ04', 6, 5, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Σχεδίαση Ψηφιακών Συστημάτων - VHDL', 'ΥΣ03', 6, 5, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Τεχνητή Νοημοσύνη I', 'ΥΣ02', 6, 5, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Τηλεπικοινωνιακά Δίκτυα', 'ΕΠ20', 6, 5, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Υλοποίηση Συστημάτων Βάσεων Δεδομένων', 'K18', 6, 5, 'NotTaken', 'TrackCompulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ψηφιακή Επεξεργασία Σήματος', 'K32', 6, 5, 'NotTaken', 'TrackCompulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Αλγόριθμοι-Θεμελιώσεις Μηχανικής Μάθησης', 'ΘΠ16β', 6, 6, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Αναγνώριση Προτύπων–Μηχανική Μάθηση', 'ΕΠ08', 6, 6, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ανάλυση/Σχεδίαση Συστημάτων Λογισμικού', 'ΥΣ04', 6, 6, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ασύρματα Δίκτυα Αισθητήρων', 'ΥΣ18', 6, 6, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Διαχείριση Δικτύων', 'Κ34', 6, 6, 'NotTaken', 'TrackCompulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ειδικά Θέματα Επικοινωνιών και Επεξεργασίας Σήματος – Πολυμέσα και Ασύρματη Δικτύωση', 'ΕΠ22β', 4, 6, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Επεξεργασία Στοχαστικών Σημάτων', 'ΕΠ07', 6, 6, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Επιστημονικοί Υπολογισμοί', 'ΘΠ03', 6, 6, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Εργαστήριο Ηλεκτρονικής', 'Κ19ε', 6, 6, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ηλεκτρονική', 'K19', 6, 6, 'NotTaken', 'TrackCompulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Θεωρία Πληροφορίας και Κωδίκων', 'Κ35', 6, 6, 'NotTaken', 'TrackCompulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Θεωρία Υπολογισμού', 'Κ25', 6, 6, 'NotTaken', 'TrackCompulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Λογικός Προγραμματισμός', 'ΥΣ05', 6, 6, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Μαθηματικά Πληροφορικής', 'Κ20α', 6, 6, 'NotTaken', 'TrackCompulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Μεταγλωττιστές', 'Κ31', 6, 6, 'NotTaken', 'TrackCompulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Προγραμματισμός Συστήματος', 'Κ24', 8, 6, 'NotTaken', 'Compulsory');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Τεχνητή Νοημοσύνη ΙΙ (Βαθιά Μηχανική Μάθηση για την Επεξεργασία Φυσικής Γλώσσας)', 'ΥΣ19', 6, 6, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Τεχνικές Εξόρυξης Δεδομένων', 'ΥΣ11', 6, 6, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Τεχνολογίες Εφαρμογών Διαδικτύου', 'ΥΣ14', 6, 6, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Αλγοριθμική Επιχειρησιακή Έρευνα', 'ΘΠ09', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ανάπτυξη Λογισμικού για Αλγοριθμικά Προβλήματα', 'Κ23γ', 8, 7, 'NotTaken', 'Project');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ανάπτυξη Λογισμικού για Πληροφοριακά Συστήματα', 'Κ23α', 8, 7, 'NotTaken', 'Project');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ανάπτυξη Λογισμικού για Συστήματα Δικτύων και Τηλεπικοινωνιών', 'Κ23β', 8, 7, 'NotTaken', 'Project');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Διδακτική της Πληροφορικής', 'ΥΣ10', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Δομή και Θεσμοί της Ευρωπαϊκής Ένωσης', 'ΓΠ03', 2, 7, 'NotTaken', 'GeneralEd');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ειδικά Θέματα Επικοινωνιών και Επεξεργασίας Σήματος: Ειδικά Θέματα Κβαντικής Πληροφορίας και Υπολογιστικής', 'ΕΠ22δ', 4, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ειδικά Θέματα Υπολογιστικών Συστημάτων και Εφαρμογών', 'ΥΣ16', 4, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ειδικά Θέματα Υπολογιστικών Συστημάτων και Εφαρμογών – Τεχνολογίες Γνώσεων', 'ΥΣ16β', 4, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ενισχυτική Μηχανική Μάθηση και Στοχαστικά Παίγνια', 'ΕΠ22α', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Επικοινωνία Ανθρώπου Μηχανής', 'ΥΣ08', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ηλεκτρονική Διακυβέρνηση', 'ΥΣ17', 4, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Θεωρία Αριθμών', 'ΘΠ08', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Οπτικές Επικοινωνίες και Οπτικά Δίκτυα', 'ΕΠ16', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Πληροφοριακά Συστήματα', 'ΥΣ07', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Προηγμένα Θέματα Αλγορίθμων', 'ΘΠ12', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Προηγμένοι Επιστημονικοί Υπολογισμοί', 'ΘΠ18', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Συστήματα Κινητών και Προσωπικών Επικοινωνιών', 'ΕΠ18', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Συστήματα Ψηφιακής Επεξεργασίας Σημάτων σε Πραγματικό Χρόνο', 'ΕΠ11', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Σχεδίαση VLSI Κυκλωμάτων', 'ΕΠ01', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Τεχνολογίες της Πληροφορίας και των Επικοινωνιών (ΤΠΕ) στη Μάθηση', 'ΥΣ15', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Υπολογιστική Πολυπλοκότητα', 'ΘΠ20', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ψηφιακή Προσβασιμότητα και Υποστηρικτικές Τεχνολογίες Πληροφορικής', 'ΥΣ22', 6, 7, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Αλγοριθμική Επίλυση Προβλημάτων', 'ΘΠ24', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ανάλυση Εικόνας και Τεχνητή Όραση', 'ΕΠ23', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ανάπτυξη Υλικού-Λογισμικού για Ενσωματωμένα Συστήματα', 'Κ23δ', 8, 8, 'NotTaken', 'Project');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ασύρματες Zεύξεις', 'ΕΠ13', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Διοίκηση Έργων και Τεχνικές Παρουσίασης και Συγγραφής Επιστημονικών Εκθέσεων', 'ΓΠ05', 2, 8, 'NotTaken', 'GeneralEd');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ειδικά Θέματα Επικοινωνιών και Επεξεργασίας Σήματος: Γραμμές μεταφοράς, κυματοδηγοί και οπτικές ίνες', 'ΕΠ22γ', 4, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ειδικά Θέματα Επικοινωνιών και Επεξεργασίας Σήματος: Ειδικά Θέματα Κβαντικής Μηχανικής Μάθησης', 'ΕΠ22ε', 4, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ειδικά Θέματα Θεωρητικής Πληροφορικής: Αλγόριθμοι Δομικής Βιοπληροφορικής', 'ΘΠ16δ', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ειδικά Θέματα Υπολογιστικών Συστημάτων και Εφαρμογών', 'ΥΣ16', 4, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ειδικά Θέματα Υπολογιστικών Συστημάτων και Εφαρμογών: Υπολογιστικά Συστήματα Μεγάλης Κλίμακας', 'ΥΣ16α', 4, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Επεξεργασία Εικόνας', 'ΕΠ10', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Επεξεργασία Ομιλίας και Φυσικής Γλώσσας', 'ΕΠ19', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Θεωρία Γραφημάτων', 'ΘΠ10', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ιστορία της Πληροφορικής και των Τηλεπικοινωνιών', 'ΥΣ20', 4, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Καινοτομία και Επιχειρηματικότητα', 'ΥΣ12', 4, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Κρυπτογραφία', 'ΘΠ05', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Μικροοικονομική Ανάλυση', 'ΕΠ24', 4, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Μουσική Πληροφορική', 'ΕΠ21', 4, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Παράλληλοι Αλγόριθμοι', 'ΘΠ19', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Προστασία και Ασφάλεια Υπολογιστικών Συστημάτων', 'ΥΣ13', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Σημασιολογία Γλωσσών Προγραμματισμού', 'ΘΠ16α', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Σχολική Τάξη & Μικροδιδασκαλία', 'ΥΣ21', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Τεχνολογία Λογισμικού', 'ΥΣ09', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Υπολογιστική Γεωμετρία', 'ΘΠ11', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Υπολογιστική Θεωρία Μηχανικής Μάθησης', 'ΘΠ23', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Φωτονική', 'ΕΠ12', 6, 8, 'NotTaken', 'Elective');
INSERT INTO courses (name, code, ects, semester, status, type) VALUES ('Ψηφιακές Επικοινωνίες', 'ΕΠ04', 6, 8, 'NotTaken', 'Elective');
