name: Backend CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    
jobs:
  run-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Ensure clean database state
        run: rm -f courses.db

      - name: Run server in background
        run: uvicorn server:app --host 0.0.0.0 --port 8000 &

      - name: Wait for server to be ready
        run: |
          echo "Waiting for server..."
          while ! curl -s http://localhost:8000/api/courses > /dev/null; do
            sleep 1
          done
          echo "Server is up!"

      - name: Test /api/courses endpoint
        run: curl --fail http://localhost:8000/api/courses | jq .

      - name: Test /api/profile endpoint
        run: response=$(curl --fail -s http://localhost:8000/api/profile)
          echo "$response" | jq -e '.sdi == 2400120'
          
      - name: Update course status
        run: |
          curl --fail -X PUT \
            -H "Content-Type: application/json" \
            -d '{"status": "Passed"}' \
            http://localhost:8000/api/courses/1/status

      - name: Update course grade
        run: |
          curl --fail -X PUT \
          -H "Content-Type: application/json" \
          -d '{"grade": 8}' \
          http://localhost:8000/api/courses/1/grade

      - name: Update course planned semester
        run: |
          curl --fail -X PUT \
          -H "Content-Type: application/json" \
          -d '{"planned_semester": 3}' \
          http://localhost:8000/api/courses/1/planned_semester

      - name: Verify course status was updated
        run: |
          curl -s http://localhost:8000/api/courses | jq -e '.[] | select(.id == 1) | .status == "Passed"'
          
      - name: Verify course grade was updated
        run: |
          curl -s http://localhost:8000/api/courses | jq -e '.[] | select(.id == 1) | .grade == 8.0'

      - name: Verify course planned semester was updated
        run: |
          curl -s http://localhost:8000/api/courses | jq -e '.[] | select(.id == 1) | .planned_semester == 3'

      - name: Reset course status
        run: |
          curl --fail -X PUT \
            -H "Content-Type: application/json" \
            -d '{"status": "Not Taken"}' \
            http://localhost:8000/api/courses/1/status

      - name: Verify course status was reset
        run: |
          curl -s http://localhost:8000/api/courses | jq -e '.[] | select(.id == 1) | .status == "Not Taken"'
