jobs:
  run-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Backup original DB
        run: cp courses.db courses.db.orig

      - name: Run server in background
        run: python3 server.py &

      - name: Wait for server to start
        run: sleep 10

      - name: Test /api/courses endpoint
        run: curl --fail http://localhost:8000/api/courses

      - name: Update course status
        run: |
          curl --fail -X PUT \
            -H "Content-Type: application/json" \
            -d '{"status": "Passed"}' \
            http://localhost:8000/api/courses/1/status

      - name: Verify course status was updated
        run: |
          RESPONSE=$(curl -s http://localhost:8000/api/courses/1)
          echo "$RESPONSE" | grep -q '"status":"Passed"'

      - name: Restore DB
        run: cp courses.db.orig courses.db